---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker2
spec:
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
        id: "2"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        resources:
          limits:
            memory: "1G"
            cpu: "1000m"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092,OUTSIDE://:9094
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kafka2-service:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          # value: zoo1:2181,zoo2:2181,zoo3:2181
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_CREATE_TOPICS
          value: gamebooks:1:1,users:1:1
          # value: gamebooks:12:4,users:12:4
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2-service
  labels:
    name: kafka2
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka2-port-9092
    protocol: TCP
  - port: 31090
    targetPort: 31090
    name: kafka2-port-31090
    protocol: TCP
  selector:
    app: kafka2
    id: "2"
  type: LoadBalancer