module.exports = {
  projects: [
    ,
    '<rootDir>/apps/api',
    '<rootDir>/apps/nubia-reader',
    '<rootDir>/libs/api/data-models/gamebook',
    '<rootDir>/libs/api/data-models/user',
    '<rootDir>/libs/api/data-models/chapter',
    '<rootDir>/libs/api/data-models/reading-session',
    '<rootDir>/libs/api/data-models/progression',
    '<rootDir>/libs/nubia-reader/data-access/gamebook-library',
    '<rootDir>/libs/nubia-reader/shell',
    '<rootDir>/libs/nubia-reader/features/book-shelf',
    '<rootDir>/libs/nubia-reader/ui',
    '<rootDir>/libs/nubia-reader/features/reading',
    '<rootDir>/libs/api/reader-api',
    '<rootDir>/libs/api/db-client',
    '<rootDir>/libs/api/auth',
    '<rootDir>/libs/nubia-reader/features/auth',
  ],
};
