---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker5
spec:
  selector:
    matchLabels:
      app: kafka5
  template:
    metadata:
      labels:
        app: kafka5
        id: "5"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
          hostPort: 9095
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9095"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka5-service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka5-service:9095
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: KAFKA_BROKER_ID
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka5-service
  labels:
    name: kafka5
spec:
  ports:
  - port: 9092
    targetPort: 9095
    name: kafka5-port
    protocol: TCP
  selector:
    app: kafka5
    id: "5"
  type: LoadBalancer