---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker3
spec:
  selector:
    matchLabels:
      app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
        id: "3"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        resources:
          limits:
            memory: "1G"
            cpu: "1000m"
        ports:
        - containerPort: 9092
          hostPort: 9093
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9093"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka3-service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka3-service:9093
        - name: KAFKA_ZOOKEEPER_CONNECT
          # value: zoo1:2181,zoo2:2181,zoo3:2181
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3-service
  labels:
    name: kafka3
spec:
  ports:
  - port: 9092
    targetPort: 9093
    name: kafka3-port
    protocol: TCP
  selector:
    app: kafka3
    id: "3"
  type: LoadBalancer