---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker1
spec:
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
        id: "1"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        resources:
          limits:
            memory: "1G"
            cpu: "1000m"
        ports:
        - containerPort: 9092
          hostPort: 9091
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9091"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka1-service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka1-service:9091
        - name: KAFKA_ZOOKEEPER_CONNECT
          # value: zoo1:2181,zoo2:2181,zoo3:2181
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1-service
  labels:
    name: kafka1
spec:
  ports:
  - port: 9091
    targetPort: 9092
    name: kafka1-port
    protocol: TCP
  selector:
    app: kafka1
    id: "1"
  type: LoadBalancer