apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nickfrei/nubia.api-gateway
          resources:
            limits:
              cpu: "500m"
              memory: "2G"
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: PORT
              value: "3000"
            - name: API_PREFIX
              value: "api"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-srv
spec:
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nb-service
  labels:
    name: api-gateway
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: api-gw-3000
    protocol: TCP
  selector:
    app: api-gateway
  type: NodePort