apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-editor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-editor
  template:
    metadata:
      labels:
        app: web-editor
    spec:
      containers:
      - name: web-editor
        image: nickfrei/nubia.web-editor
        resources:
          limits:
            memory: "2G"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-editor-srv
spec:
  selector:
    app: web-editor
  ports:
    - name: web-editor
      protocol: TCP
      port: 3000
      targetPort: 3000