apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: kafka.nubia.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-service
                port:
                  number: 9092
    - host: nubia.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway-srv
                port: 
                  number: 3000
          - path: /services/auth
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port: 
                  number: 3000
          - path: /services/gamebook
            pathType: Prefix
            backend:
              service:
                name: gamebook-srv
                port: 
                  number: 3000
          - path: /services/library
            pathType: Prefix
            backend:
              service:
                name: library-srv
                port: 
                  number: 3000
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: client-srv
          #       port: 
          #         number: 3000