import { Chapter } from '@prisma/client';

export const chapters: Chapter[] = [
  //gb 1
  {
    id: '1',
    gamebookId: '1',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '2',
    gamebookId: '1',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '3',
    gamebookId: '1',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '4',
    gamebookId: '1',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '5',
    gamebookId: '1',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  //gb 2
  {
    id: '6',
    gamebookId: '2',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '7',
    gamebookId: '2',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '8',
    gamebookId: '2',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '9',
    gamebookId: '2',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '10',
    gamebookId: '2',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  // gb 3
  {
    id: '11',
    gamebookId: '3',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',

    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '12',
    gamebookId: '3',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '13',
    gamebookId: '3',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '14',
    gamebookId: '3',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '15',
    gamebookId: '3',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  // gb 4
  {
    id: '16',
    gamebookId: '4',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '17',
    gamebookId: '4',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '18',
    gamebookId: '4',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '19',
    gamebookId: '4',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '20',
    gamebookId: '4',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  // gb 5
  {
    id: '21',
    gamebookId: '5',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',

    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '22',
    gamebookId: '5',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '23',
    gamebookId: '5',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '24',
    gamebookId: '5',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '25',
    gamebookId: '5',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  // gb 6
  {
    id: '26',
    gamebookId: '6',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',

    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '27',
    gamebookId: '6',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '28',
    gamebookId: '6',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '29',
    gamebookId: '6',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '30',
    gamebookId: '6',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  // gb 7
  {
    id: '31',
    gamebookId: '7',
    isStartingChapter: true,
    isEndingChapter: false,
    title: 'Enemy Of Dusk',

    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '32',
    gamebookId: '7',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Foreigner Of Nightmares',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '33',
    gamebookId: '7',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Gods Of Fire',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '34',
    gamebookId: '7',
    isStartingChapter: false,
    isEndingChapter: false,
    title: 'Bandits Of The North',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
  {
    id: '35',
    gamebookId: '7',
    isStartingChapter: false,
    isEndingChapter: true,
    title: 'Phantoms And Aliens',
    content: `<p>Curabitur tortor. Pellentesque nibh. Aenean quam. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. </p>`,
  },
];
